//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLoginData
    {
        public int AccountLoginDataID { get; set; }
        public string AccountLoginDataUserName { get; set; }
        public string AccountLoginDataPassword { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string AccountName { get; set; }
    
        public virtual LoginInformation LoginInformation { get; set; }
    }
}
