<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="PasswordWebApp.Home" %>
<%@ Register Src="~/headerContentForOtherPages.ascx" TagPrefix="uc1" TagName="headerContentForOtherPages" %>
<%@ Register Src="~/Footer.ascx" TagPrefix="uc1" TagName="Footer" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    
<head runat="server">
    <title>Home</title>
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" />   
     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
     <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css" />
      <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
       <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
     <script>
         $(document).ready(function () {
             $('#PasswordDataGrid').dataTable();
         });
        
    </script>             
</head>
    <body class="body">
        <form id="form1" runat="server">
    <div class="container-fluid">
        <section class="header">
            <div class="page-header">
                 <uc1:headerContentForOtherPages runat="server" ID="headerContentForOtherPages" />
            </div>
        </section>
      <div class="row">
          <br />
          <div class="col-md-6">
            <span>Search:</span><asp:TextBox TextMode="Search" runat="server" ID="txtSearchData" />&nbsp <asp:Button CssClass="btn-success" Text="Search" runat="server" ID="btnSearch" OnClick="btnSearch_Click"/>
          </div>
        <div class ="col-md-4">
            Sort by: &nbsp
           <label class="radio-inline">
               <span></span><asp:RadioButton Checked="false" Text="AccountName" ID="rbtnAccountName" runat="server" />
           </label>
            <label class="radio-inline">
                <asp:RadioButton Checked="false" Text="UserName" ID="rbtnUserName" runat="server" />
            </label>
            <label class="radio-inline">
                <asp:RadioButton Checked="false" Text="Password" ID="rbtnPassword" runat="server" />
            </label>
            <br />
            <asp:Label CssClass="label-danger" runat="server" ID="lblNoRecordFound" Visible ="false" />
        </div>
          <br />
          <div class="col-md-12">
             <a href="AddAccount.aspx">Add an account</a>
              <br />
             <asp:DataGrid ID="PasswordDataGrid" 
                  AutoGenerateColumns="false"
                  OnEditCommand="PasswordDataGrid_EditCommand"
                  runat="server" CssClass="table table-striped table-bordered dt-responsive nowrap">
                  <HeaderStyle BackColor="#00aaaa">
                  </HeaderStyle>
                  <Columns>
                      <asp:BoundColumn DataField="AccountName" ReadOnly="true" HeaderText="Account Name" />
                      <asp:BoundColumn DataField="AccountLoginDataUserName" ReadOnly="true" HeaderText="User Name"></asp:BoundColumn>
                      <asp:BoundColumn DataField="AccountLoginDataPassword" ReadOnly="true" HeaderText="Password"></asp:BoundColumn>
                      <asp:EditCommandColumn ButtonType="LinkButton" Visible="true" EditText="Edit" CancelText="Cancel" />
                  
                    </Columns>
              </asp:DataGrid>
              <%--<asp:GridView ID="PasswordGridView" runat="server" 
                  OnRowEditing="PasswordGridView_RowEditing" 
                  OnRowDeleting="PasswordGridView_RowDeleting"
                  CssClass="table table-striped table-bordered dt-responsive nowrap"
                  AutoGeneratedColumns="false">
                  <HeaderStyle BackColor="#00aaaa">
                  </HeaderStyle>
                  <Columns>
                      <asp:BoundField DataField="AccountName" HeaderText="Account Name" />
                      <asp:BoundField DataField="AccountLoginDataUserName" HeaderText="User Name" />
                      <asp:BoundField DataField="AccountLoginDataPassword" HeaderText="Password" />
                  </Columns>
              </asp:GridView>--%>

          </div>
      </div>
        <section class="footer">
            <uc1:Footer runat="server" ID="Footer" />
        </section>
    </div>
    </form>
</body>
</html> 
