//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInformation
    {
        public LoginInformation()
        {
            this.AccountLoginDatas = new HashSet<AccountLoginData>();
        }
    
        public int LoginID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<AccountLoginData> AccountLoginDatas { get; set; }
        public virtual Person Person { get; set; }
    }
}
